"""some typo was fixed

Revision ID: ca9d35377a47
Revises: d6e865ed84bf
Create Date: 2025-09-12 21:50:53.433664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca9d35377a47'
down_revision = 'd6e865ed84bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shop_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_bookmarks_shop_id'), type_='foreignkey')
        batch_op.create_foreign_key('fk_bookmarks_shop_id', 'shop', ['shop_id'], ['id'])
        batch_op.drop_column('shop.id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shop.id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint('fk_bookmarks_shop_id', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_bookmarks_shop_id'), 'shop', ['shop.id'], ['id'])
        batch_op.drop_column('shop_id')

    # ### end Alembic commands ###
