"""add bookmarks relationship

Revision ID: d6e865ed84bf
Revises: 44bdba5cbd1a
Create Date: 2025-09-12 21:23:29.734753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6e865ed84bf'
down_revision = '44bdba5cbd1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmarks',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('shop.id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['shop.id'], ['shop.id'], name='fk_bookmarks_shop_id'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_bookmarks_user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookmarks')
    # ### end Alembic commands ###
