"""add followers relationship

Revision ID: e0de913c7c3e
Revises: b1fa79083d01
Create Date: 2025-09-06 09:56:10.247019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0de913c7c3e'
down_revision = 'b1fa79083d01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], name='fk_followers_followed_id'),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], name='fk_followers_follower_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
